[
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 0, 0], // Inst { req_angle: 0, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 128, 0, 0], // Inst { req_angle: 1, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 128, 0, 0], // Inst { req_angle: 1, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[1, 0, 0, 0], // Inst { req_angle: 2, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[2, 0, 4, 0], // Inst { req_angle: 4, req_odom_y: 1, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[2, 128, 20, 0], // Inst { req_angle: 5, req_odom_y: 5, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[4, 0, 32, 0], // Inst { req_angle: 8, req_odom_y: 8, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[5, 128, 48, 0], // Inst { req_angle: 11, req_odom_y: 12, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[7, 0, 64, 0], // Inst { req_angle: 14, req_odom_y: 16, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[8, 128, 84, 0], // Inst { req_angle: 17, req_odom_y: 21, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[10, 0, 104, 0], // Inst { req_angle: 20, req_odom_y: 26, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[12, 0, 132, 0], // Inst { req_angle: 24, req_odom_y: 33, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[14, 0, 156, 0], // Inst { req_angle: 28, req_odom_y: 39, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[16, 0, 184, 0], // Inst { req_angle: 32, req_odom_y: 46, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[18, 0, 204, 0], // Inst { req_angle: 36, req_odom_y: 51, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[20, 128, 244, 0], // Inst { req_angle: 41, req_odom_y: 61, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[23, 1, 8, 0], // Inst { req_angle: 46, req_odom_y: 66, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[26, 1, 48, 0], // Inst { req_angle: 52, req_odom_y: 76, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[28, 129, 76, 0], // Inst { req_angle: 57, req_odom_y: 83, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[31, 129, 116, 0], // Inst { req_angle: 63, req_odom_y: 93, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[34, 1, 144, 0], // Inst { req_angle: 68, req_odom_y: 100, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[36, 1, 180, 0], // Inst { req_angle: 72, req_odom_y: 109, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[37, 129, 196, 0], // Inst { req_angle: 75, req_odom_y: 113, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[38, 129, 212, 0], // Inst { req_angle: 77, req_odom_y: 117, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[39, 1, 212, 0], // Inst { req_angle: 78, req_odom_y: 117, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[39, 1, 212, 0], // Inst { req_angle: 78, req_odom_y: 117, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[39, 1, 212, 0], // Inst { req_angle: 78, req_odom_y: 117, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[39, 1, 212, 0], // Inst { req_angle: 78, req_odom_y: 117, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[39, 1, 212, 0], // Inst { req_angle: 78, req_odom_y: 117, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[39, 1, 212, 0], // Inst { req_angle: 78, req_odom_y: 117, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[39, 1, 212, 0], // Inst { req_angle: 78, req_odom_y: 117, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[39, 1, 212, 0], // Inst { req_angle: 78, req_odom_y: 117, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[39, 1, 212, 0], // Inst { req_angle: 78, req_odom_y: 117, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[39, 1, 212, 0], // Inst { req_angle: 78, req_odom_y: 117, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[39, 1, 212, 0], // Inst { req_angle: 78, req_odom_y: 117, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[39, 129, 220, 0], // Inst { req_angle: 79, req_odom_y: 119, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[39, 129, 224, 0], // Inst { req_angle: 79, req_odom_y: 120, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[40, 1, 232, 0], // Inst { req_angle: 80, req_odom_y: 122, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[41, 1, 236, 0], // Inst { req_angle: 82, req_odom_y: 123, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[42, 1, 252, 0], // Inst { req_angle: 84, req_odom_y: 127, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[43, 2, 12, 0], // Inst { req_angle: 86, req_odom_y: 131, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[44, 130, 28, 0], // Inst { req_angle: 89, req_odom_y: 135, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[45, 2, 36, 0], // Inst { req_angle: 90, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[44, 2, 36, 0], // Inst { req_angle: 88, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[43, 130, 32, 0], // Inst { req_angle: 87, req_odom_y: 136, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[42, 2, 12, 0], // Inst { req_angle: 84, req_odom_y: 131, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[40, 129, 248, 0], // Inst { req_angle: 81, req_odom_y: 126, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[38, 129, 224, 0], // Inst { req_angle: 77, req_odom_y: 120, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[36, 129, 196, 0], // Inst { req_angle: 73, req_odom_y: 113, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[34, 129, 176, 0], // Inst { req_angle: 69, req_odom_y: 108, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[32, 129, 148, 0], // Inst { req_angle: 65, req_odom_y: 101, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[30, 129, 128, 0], // Inst { req_angle: 61, req_odom_y: 96, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[28, 129, 100, 0], // Inst { req_angle: 57, req_odom_y: 89, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[26, 129, 80, 0], // Inst { req_angle: 53, req_odom_y: 84, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[24, 1, 48, 0], // Inst { req_angle: 48, req_odom_y: 76, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[21, 129, 28, 0], // Inst { req_angle: 43, req_odom_y: 71, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[19, 128, 248, 0], // Inst { req_angle: 39, req_odom_y: 62, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[17, 0, 228, 0], // Inst { req_angle: 34, req_odom_y: 57, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[15, 0, 196, 0], // Inst { req_angle: 30, req_odom_y: 49, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[13, 0, 176, 0], // Inst { req_angle: 26, req_odom_y: 44, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[11, 0, 140, 0], // Inst { req_angle: 22, req_odom_y: 35, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[8, 128, 116, 0], // Inst { req_angle: 17, req_odom_y: 29, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[6, 128, 80, 0], // Inst { req_angle: 13, req_odom_y: 20, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[4, 0, 52, 0], // Inst { req_angle: 8, req_odom_y: 13, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[1, 128, 12, 0], // Inst { req_angle: 3, req_odom_y: 3, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 248, 0], // Inst { req_angle: -1, req_odom_y: -2, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 127, 220, 0], // Inst { req_angle: -4, req_odom_y: -9, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[252, 255, 212, 0], // Inst { req_angle: -7, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 127, 212, 0], // Inst { req_angle: -6, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 127, 212, 0], // Inst { req_angle: -6, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 255, 212, 0], // Inst { req_angle: -5, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 255, 212, 0], // Inst { req_angle: -5, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 255, 212, 0], // Inst { req_angle: -5, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 255, 212, 0], // Inst { req_angle: -5, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 255, 212, 0], // Inst { req_angle: -5, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 255, 212, 0], // Inst { req_angle: -5, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 255, 212, 0], // Inst { req_angle: -5, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 255, 212, 0], // Inst { req_angle: -5, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 255, 212, 0], // Inst { req_angle: -5, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 127, 212, 0], // Inst { req_angle: -4, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 127, 212, 0], // Inst { req_angle: -4, req_odom_y: -11, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 255, 220, 0], // Inst { req_angle: -3, req_odom_y: -9, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 224, 0], // Inst { req_angle: -1, req_odom_y: -8, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 127, 228, 0], // Inst { req_angle: 0, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 127, 228, 0], // Inst { req_angle: 0, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 228, 0], // Inst { req_angle: -1, req_odom_y: -7, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 232, 0], // Inst { req_angle: -1, req_odom_y: -6, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 236, 0], // Inst { req_angle: -1, req_odom_y: -5, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 248, 0], // Inst { req_angle: -1, req_odom_y: -2, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 128, 0, 0], // Inst { req_angle: -1, req_odom_y: 0, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 128, 16, 0], // Inst { req_angle: -1, req_odom_y: 4, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 128, 32, 0], // Inst { req_angle: -1, req_odom_y: 8, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 128, 56, 0], // Inst { req_angle: -1, req_odom_y: 14, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 128, 72, 0], // Inst { req_angle: -1, req_odom_y: 18, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 128, 100, 0], // Inst { req_angle: -1, req_odom_y: 25, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 128, 124, 0], // Inst { req_angle: -1, req_odom_y: 31, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 128, 160, 0], // Inst { req_angle: -1, req_odom_y: 40, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 128, 184, 0], // Inst { req_angle: -1, req_odom_y: 46, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 128, 224, 0], // Inst { req_angle: -1, req_odom_y: 56, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 128, 248, 0], // Inst { req_angle: -1, req_odom_y: 62, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 1, 36, 0], // Inst { req_angle: -2, req_odom_y: 73, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 1, 60, 0], // Inst { req_angle: -2, req_odom_y: 79, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 1, 100, 0], // Inst { req_angle: -2, req_odom_y: 89, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 1, 128, 0], // Inst { req_angle: -2, req_odom_y: 96, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 1, 164, 0], // Inst { req_angle: -2, req_odom_y: 105, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 1, 188, 0], // Inst { req_angle: -2, req_odom_y: 111, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 1, 228, 0], // Inst { req_angle: -2, req_odom_y: 121, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 1, 252, 0], // Inst { req_angle: -2, req_odom_y: 127, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 2, 36, 0], // Inst { req_angle: -2, req_odom_y: 137, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 130, 64, 0], // Inst { req_angle: -3, req_odom_y: 144, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 130, 104, 0], // Inst { req_angle: -3, req_odom_y: 154, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 130, 132, 0], // Inst { req_angle: -3, req_odom_y: 161, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 2, 176, 0], // Inst { req_angle: -2, req_odom_y: 172, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 2, 204, 0], // Inst { req_angle: -2, req_odom_y: 179, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 2, 244, 0], // Inst { req_angle: -2, req_odom_y: 189, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 3, 12, 0], // Inst { req_angle: -2, req_odom_y: 195, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 3, 52, 0], // Inst { req_angle: -2, req_odom_y: 205, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 3, 80, 0], // Inst { req_angle: -2, req_odom_y: 212, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 3, 128, 0], // Inst { req_angle: -2, req_odom_y: 224, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 3, 156, 0], // Inst { req_angle: -2, req_odom_y: 231, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 3, 204, 0], // Inst { req_angle: -2, req_odom_y: 243, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 3, 236, 0], // Inst { req_angle: -2, req_odom_y: 251, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 254, 32, 0], // Inst { req_angle: -3, req_odom_y: -120, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 126, 92, 0], // Inst { req_angle: -2, req_odom_y: -105, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 254, 128, 0], // Inst { req_angle: -3, req_odom_y: -96, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 126, 184, 0], // Inst { req_angle: -2, req_odom_y: -82, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 116, 0], // Inst { req_angle: -2, req_odom_y: -35, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 152, 0], // Inst { req_angle: -1, req_odom_y: -26, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 248, 0], // Inst { req_angle: -1, req_odom_y: -2, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 48, 0], // Inst { req_angle: 0, req_odom_y: 12, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 0, 176, 0], // Inst { req_angle: 0, req_odom_y: 44, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[5, 127, 0, 0], // Inst { req_angle: 10, req_odom_y: -64, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[4, 255, 12, 0], // Inst { req_angle: 9, req_odom_y: -61, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[4, 255, 12, 0], // Inst { req_angle: 9, req_odom_y: -61, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[4, 255, 15, 0], // Inst { req_angle: 9, req_odom_y: -61, act_belt_active: true, act_belt_up: true, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[4, 255, 12, 0], // Inst { req_angle: 9, req_odom_y: -61, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[4, 255, 14, 0], // Inst { req_angle: 9, req_odom_y: -61, act_belt_active: true, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[5, 125, 244, 0], // Inst { req_angle: 10, req_odom_y: -131, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[4, 253, 196, 0], // Inst { req_angle: 9, req_odom_y: -143, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[4, 253, 160, 0], // Inst { req_angle: 9, req_odom_y: -152, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[4, 125, 108, 0], // Inst { req_angle: 8, req_odom_y: -165, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[4, 125, 76, 0], // Inst { req_angle: 8, req_odom_y: -173, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 131, 152, 0], // Inst { req_angle: -5, req_odom_y: 230, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 3, 128, 0], // Inst { req_angle: -4, req_odom_y: 224, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 2, 224, 0], // Inst { req_angle: -4, req_odom_y: 184, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 130, 168, 0], // Inst { req_angle: -3, req_odom_y: 170, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 130, 68, 0], // Inst { req_angle: -3, req_odom_y: 145, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 2, 24, 0], // Inst { req_angle: -2, req_odom_y: 134, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 1, 220, 0], // Inst { req_angle: -2, req_odom_y: 119, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 129, 176, 0], // Inst { req_angle: -1, req_odom_y: 108, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 129, 112, 0], // Inst { req_angle: -1, req_odom_y: 92, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 1, 68, 0], // Inst { req_angle: 0, req_odom_y: 81, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 1, 0, 0], // Inst { req_angle: 0, req_odom_y: 64, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[1, 126, 60, 0], // Inst { req_angle: 2, req_odom_y: -113, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 254, 24, 0], // Inst { req_angle: 1, req_odom_y: -122, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 253, 168, 0], // Inst { req_angle: 1, req_odom_y: -150, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 125, 144, 0], // Inst { req_angle: 0, req_odom_y: -156, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[0, 125, 52, 0], // Inst { req_angle: 0, req_odom_y: -179, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 131, 228, 0], // Inst { req_angle: -3, req_odom_y: 249, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 131, 192, 0], // Inst { req_angle: -3, req_odom_y: 240, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 131, 164, 0], // Inst { req_angle: -3, req_odom_y: 233, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 3, 128, 0], // Inst { req_angle: -4, req_odom_y: 224, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 3, 100, 0], // Inst { req_angle: -4, req_odom_y: 217, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 131, 68, 0], // Inst { req_angle: -5, req_odom_y: 209, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 131, 48, 0], // Inst { req_angle: -5, req_odom_y: 204, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 131, 20, 0], // Inst { req_angle: -5, req_odom_y: 197, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 131, 4, 0], // Inst { req_angle: -5, req_odom_y: 193, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 130, 232, 0], // Inst { req_angle: -5, req_odom_y: 186, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 130, 216, 0], // Inst { req_angle: -5, req_odom_y: 182, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 130, 188, 0], // Inst { req_angle: -5, req_odom_y: 175, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 130, 172, 0], // Inst { req_angle: -5, req_odom_y: 171, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 130, 148, 0], // Inst { req_angle: -5, req_odom_y: 165, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 130, 132, 0], // Inst { req_angle: -5, req_odom_y: 161, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[253, 130, 104, 0], // Inst { req_angle: -5, req_odom_y: 154, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 2, 84, 0], // Inst { req_angle: -4, req_odom_y: 149, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 2, 48, 0], // Inst { req_angle: -4, req_odom_y: 140, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 2, 20, 0], // Inst { req_angle: -4, req_odom_y: 133, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 1, 236, 0], // Inst { req_angle: -4, req_odom_y: 123, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 1, 212, 0], // Inst { req_angle: -4, req_odom_y: 117, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 129, 168, 0], // Inst { req_angle: -3, req_odom_y: 106, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 129, 140, 0], // Inst { req_angle: -3, req_odom_y: 99, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 129, 88, 0], // Inst { req_angle: -3, req_odom_y: 86, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 129, 52, 0], // Inst { req_angle: -3, req_odom_y: 77, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 128, 252, 0], // Inst { req_angle: -3, req_odom_y: 63, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 128, 216, 0], // Inst { req_angle: -3, req_odom_y: 54, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 128, 156, 0], // Inst { req_angle: -3, req_odom_y: 39, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[254, 128, 120, 0], // Inst { req_angle: -3, req_odom_y: 30, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 0, 56, 0], // Inst { req_angle: -2, req_odom_y: 14, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 0, 16, 0], // Inst { req_angle: -2, req_odom_y: 4, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 216, 0], // Inst { req_angle: -2, req_odom_y: -10, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 176, 0], // Inst { req_angle: -2, req_odom_y: -20, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 124, 0], // Inst { req_angle: -2, req_odom_y: -33, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 92, 0], // Inst { req_angle: -2, req_odom_y: -41, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 52, 0], // Inst { req_angle: -2, req_odom_y: -51, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 32, 0], // Inst { req_angle: -2, req_odom_y: -56, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 24, 0], // Inst { req_angle: -2, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 24, 0], // Inst { req_angle: -2, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 24, 0], // Inst { req_angle: -2, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 24, 0], // Inst { req_angle: -2, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 24, 0], // Inst { req_angle: -2, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 24, 0], // Inst { req_angle: -2, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 24, 0], // Inst { req_angle: -2, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 24, 0], // Inst { req_angle: -2, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 24, 0], // Inst { req_angle: -2, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 24, 0], // Inst { req_angle: -2, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 27, 0], // Inst { req_angle: -2, req_odom_y: -58, act_belt_active: true, act_belt_up: true, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 27, 0], // Inst { req_angle: -2, req_odom_y: -58, act_belt_active: true, act_belt_up: true, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 27, 0], // Inst { req_angle: -2, req_odom_y: -58, act_belt_active: true, act_belt_up: true, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 27, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: true, act_belt_up: true, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 27, 0], // Inst { req_angle: -2, req_odom_y: -58, act_belt_active: true, act_belt_up: true, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 27, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: true, act_belt_up: true, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 27, 0], // Inst { req_angle: -2, req_odom_y: -58, act_belt_active: true, act_belt_up: true, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 27, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: true, act_belt_up: true, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 27, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: true, act_belt_up: true, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 127, 27, 0], // Inst { req_angle: -2, req_odom_y: -58, act_belt_active: true, act_belt_up: true, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1, req_odom_y: -58, act_belt_active: false, act_belt_up: false, act_solenoid_active: false, act_doinker_active: false, act_doinker_up: false }
[255, 255, 24, 0], // Inst { req_angle: -1,
]
